# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mysite.Tag'),
        ),
    ]
